Code/YourOwnAuth2/Posts/config/routes.rb
Posts::Application.routes.draw do
  root :to => 'posts#index'
  resources :posts

  get 'sign_up' => 'users#new', :as => 'sign_up'
  resources :users

  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  resources :sessions

end

Code/YourOwnAuth2/Posts/app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title,:description

  belongs_to :user
end

Code/YourOwnAuth2/Posts/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  # Required so that only these fields are mass-assignable through a form.
  # Important since we dont want anybody to change password_hash and password_salt using mass assignment
  attr_accessible :email, :name, :password, :password_confirmation

  validates_presence_of :name, :email
  validates_presence_of :password, :on => :create
  validates_uniqueness_of :email

  has_many :posts
end

Code/YourOwnAuth2/Posts/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :authenticate!

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate!
    if(!current_user)
      session[:saved_url] = request.url
      redirect_to login_path
    end
  end
end

Code/YourOwnAuth2/Posts/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate!, :except => [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = current_user.posts.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = current_user.posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

Code/YourOwnAuth2/Posts/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  force_ssl :except => [:destroy]

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id

      ru = session[:saved_url] || root_url
      session[:saved_url] = nil
      redirect_to ru, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

Code/YourOwnAuth2/Posts/app/controllers/users_controller.rb
class UsersController < ApplicationController
  force_ssl

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id

      ru = session[:saved_url] || root_url
      session[:saved_url] = nil
      redirect_to ru, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

Code/YourOwnAuth2/Posts/app/helpers/application_helper.rb
module ApplicationHelper
end

Code/YourOwnAuth2/Posts/app/helpers/posts_helper.rb
module PostsHelper
end

Code/YourOwnAuth2/Posts/app/helpers/sessions_helper.rb
module SessionsHelper
end

Code/YourOwnAuth2/Posts/app/helpers/users_helper.rb
module UsersHelper
end

Code/YourOwnAuth2/Posts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Posts</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<%= render :partial => 'shared/header' %>

<div id="wrap">
  <div id="main" class="clear-top">
    <%= render :partial => 'shared/flash_notices' %>
    <div class="container">
      <%= yield %>
    </div>
  </div>
</div>

<%= render :partial => 'shared/footer' %>

</body>
</html>

Code/YourOwnAuth2/Posts/app/views/posts/_form.html.erb
<%= simple_form_for(@post, :html=>{:class => 'well form-horizontal'}) do |f| %>
    <%= f.input :title, :input_html => {:class => 'input-xlarge'} %>
    <%= f.input :description, :input_html => {:class => 'input-xlarge', :rows=>5} %>

    <div class="form-actions">
      <%= f.submit "Submit", :class => 'btn btn-primary btn-large' %>
      <%= link_to 'Cancel', posts_path, :class => 'btn btn-danger btn-mini' %>
    </div>
<% end %>

Code/YourOwnAuth2/Posts/app/views/posts/edit.html.erb
<%= render :partial=>'shared/jumbo_title', :locals => {:title=>'Edit Post', :action=>link_to('Show Post', @post, :class=>'btn btn-success')} %>
<%= render 'form' %>

Code/YourOwnAuth2/Posts/app/views/posts/index.html.erb
<%= render :partial=>'shared/jumbo_title', :locals => {:title=>'All Posts', :description => 'This page lists all posts on this website', :action => link_to('New Post', new_post_path, :class=>'btn btn-success')} %>

<ul class="unstyled">
<% @posts.each do |post| %>
      <li>
        <section>
          <h2><%= link_to post.title, post %></h2>
          <h3><small><%= post.user.name %></small></h3>
          <p>
            <span class="label"><%= distance_of_time_in_words_to_now(post.created_at, true) %></span>
          </p>
          <p><%= truncate(post.description, :length => 250, :omission => "... (continued)") %></p>
          <% if current_user == post.user %>
              <p>
                <%= link_to 'Edit', edit_post_path(post), :class=>'btn btn-primary btn-mini' %>
                <%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete , class: 'btn btn-danger btn-mini'%>
              </p>
          <% end %>
        </section>
      </li>
<% end %>
</ul>

Code/YourOwnAuth2/Posts/app/views/posts/new.html.erb
<%= render :partial=>'shared/jumbo_title', :locals => {:title=>'New Post'} %>
<%= render 'form' %>

Code/YourOwnAuth2/Posts/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<h2><small><%= @post.user.name %></small></h2>

<p>
  <span class="label"><%= distance_of_time_in_words_to_now(@post.created_at, true) %></span>
</p>


<p>
  <%= @post.description %>
</p>

<% if current_user == @post.user %>
    <%= link_to 'Edit', edit_post_path(@post), :class=>'btn btn-primary' %>
<% end %>
<%= link_to 'Back', posts_path, :class => 'btn btn-danger' %>

Code/YourOwnAuth2/Posts/app/views/shared/_alert.html.erb
<% alert_type = 'error' if local_assigns[:alert_type].nil? %>
<% alert_heading = nil if local_assigns[:alert_heading].nil? %>
<% alert_message = '' if local_assigns[:alert_message].nil? %>

<div class="alert alert-<%= alert_type %>">
  <% if !alert_heading.blank? %>
      <h4 class="alert-heading"><%= alert_heading %></h4>
  <% end %>

  <%= alert_message %>
</div>

Code/YourOwnAuth2/Posts/app/views/shared/_flash_notices.html.erb
<% if flash[:notice] && flash[:notice] != '' %>
    <div class="container alert">
      <a class="close" data-dismiss="alert">×</a>
      <strong>Notice: </strong><%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:error] && flash[:error] != '' %>
    <div class="container alert alert-error">
      <a class="close" data-dismiss="alert">×</a>
      <strong>Error: </strong><%= flash[:error] %>
    </div>
<% end %>
<% if flash[:alert] && flash[:alert] != '' %>
    <div class="container alert alert-error">
      <a class="close" data-dismiss="alert">×</a>
      <strong>Error: </strong><%= flash[:alert] %>
    </div>
<% end %>
<% if flash[:success] && flash[:success] != '' %>
    <div class="container alert alert-success">
      <a class="close" data-dismiss="alert">×</a>
      <strong>Success: </strong><%= flash[:success] %>
    </div>
<% end %>
<% if flash[:info] && flash[:info] != '' %>
    <div class="container alert  alert-info">
      <a class="close" data-dismiss="alert">×</a>
      <strong>Info: </strong><%= flash[:info] %>
    </div>
<% end %>

Code/YourOwnAuth2/Posts/app/views/shared/_footer.html.erb
<br />
<footer class="footer">
  <div class="container">
    <p>Copyright © 2012 <a href='http://www.linkedin.com/in/vaidyamihir'>Mihir Vaidya</a>. All rights reserved.</p>
    <p>
        <span><%= link_to 'Terms', '#' %></span>
        <span class="divider">|</span>
        <span><%= link_to 'Privacy', '#' %></span>
    </p>
  </div>
</footer>

Code/YourOwnAuth2/Posts/app/views/shared/_header.html.erb
<header>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%# .btn-navbar is used as the toggle for collapsed navbar content %>
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <%# Be sure to leave the brand out there if you want it shown %>
        <%= link_to "My Blog", root_path, :class => 'brand' %>

        <%# Everything you want hidden at 940px or less, place within here %>
        <div class="nav-collapse">
          <%# .nav, .navbar-search, .navbar-form, etc %>
          <ul class="nav pull-right">
            <% if current_user %>
                <li>
                  <%= link_to "Welcome #{current_user.name}!", 'javascript:void(0)' %>
                </li>
                <li>
                  <%= link_to 'Log out', logout_path %>
                </li>
            <% else %>
                <li>
                  <%= link_to 'Sign up', sign_up_path %>
                </li>
                <li>
                  <%= link_to 'Log in', login_path %>
                </li>
            <% end %>

          </ul>
        </div>
      </div>
    </div>
  </div>
</header>

Code/YourOwnAuth2/Posts/app/views/shared/_header_with_logininfo.html.erb
<header>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%# .btn-navbar is used as the toggle for collapsed navbar content %>
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <%# Be sure to leave the brand out there if you want it shown %>
        <%= link_to t('brand'), root_path, :class => 'brand' %>

        <%# Everything you want hidden at 940px or less, place within here %>
        <div class="nav-collapse">
          <%# .nav, .navbar-search, .navbar-form, etc %>
          <ul class="nav">
            <% if !user_signed_in? %>
                <li<%= controller_name == 'home' ? " class='active'" : "" %>>
                  <%= link_to t('header.home'), root_path %>
                </li>
                <li<%= controller_name == 'gallery' ? " class='active'" : "" %>>
                  <%= link_to t('header.public_gallery'), gallery_path %>
                </li>
            <% else %>
                <li<%= controller_name == 'gallery' ? " class='active'" : "" %>>
                  <%= link_to t('header.public_gallery'), gallery_path %>
                </li>
                <li<%= controller_name == 'users' ? " class='active'" : "" %>>
                  <%= link_to t('header.gallery'), friendly_user_path(current_user) %>
                </li>
                <li<%= controller_name == 'widgets' ? " class='active'" : "" %>>
                  <%= link_to t('header.widgets'), widgets_path %>
                </li>
                <li<%= controller_name == 'themes' ? " class='active'" : "" %>>
                  <%= link_to t('header.themes'), themes_path %>
                </li>
                <li<%= controller_name == 'networks' ? " class='active'" : "" %>>
                  <%= link_to t('header.networks'), networks_path %>
                </li>
            <% end %>
          </ul>
          <ul class="nav pull-right">
            <li>
              <%= link_to t('header.faq'), faqs_path %>
            </li>
            <% if !user_signed_in? %>
            <li>
              <%= link_to t('header.sign_up'), new_user_registration_path %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t('header.sign_in') %>
                <b class="caret"></b>
              </a>
              <div class="dropdown-menu">
                <%= render :partial => "users/sessions/custom_login_form" %>
              </div>
            </li>
            <% else %>
                <li>
                  <%= link_to t("header.address", :name => current_user.name), edit_user_registration_path %>
                </li>
                <li>
                  <%= link_to t('header.sign_out'), destroy_user_session_path, :method => :delete %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>

Code/YourOwnAuth2/Posts/app/views/shared/_jumbo_title.html.erb
<% title = nil if local_assigns[:title].nil? %>
<% description = nil if local_assigns[:description].nil? %>
<% action = nil if local_assigns[:action].nil? %>

<div class="jumbotron subhead">
  <h1>
    <%= title %>
  </h1>
  <% if description %>
    <p class="lead"><%= description %></p>
  <% end %>
</div>
<% if action %>
    <%= action %>
<% end %>

<hr />

Code/YourOwnAuth2/Posts/app/views/users/new.html.erb
<%= render :partial=>'shared/jumbo_title', :locals => {:title=>'Sign up'} %>

<%= simple_form_for(@user, :html=>{:class => 'well form-horizontal'}) do |f| %>
    <%= f.input :email, :input_html => {:class => 'input-xlarge'} %>
    <%= f.input :name, :input_html => {:class => 'input-xlarge'} %>
    <%= f.input :password, :as => 'password', :input_html => {:class => 'input-xlarge'} %>
    <%= f.input :password_confirmation, :as => 'password', :input_html => {:class => 'input-xlarge'} %>

    <div class="form-actions">
      <%= f.submit "Submit", :class => 'btn btn-primary btn-large' %>
      <%= link_to 'Cancel', root_path, :class => 'btn btn-danger btn-mini' %>
    </div>
<% end %>